version: '3.9'

services:

  api:
    container_name: blog-api
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    depends_on:
      - db
      - redis

  db:
    container_name: blog-db
    image: mysql:8.0
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "blog-api"

  redis:
    container_name: blog-redis
    image: redis:latest
    ports:
      - 6379:6379